openfun/fun-richie-site-factory

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/src/backend/ademe/settings.py
sites/ademe/src/backend/locale/fr/LC_MESSAGES/django.po
sites/ademe/src/backend/templates/courses/cms/course_detail.html
sites/ademe/src/backend/templates/richie/base.html
sites/ademe/src/backend/templates/social-networks/blogpost-badges.html
sites/ademe/src/backend/templates/social-networks/course-badges.html
sites/ademe/src/backend/templates/social-networks/footer-badges.html
sites/funcampus/CHANGELOG.md
sites/funcampus/src/backend/templates/social-networks/blogpost-badges.html
sites/funcampus/src/backend/templates/social-networks/course-badges.html
sites/funcampus/src/backend/templates/social-networks/footer-badges.html
sites/funcorporate/CHANGELOG.md
sites/funcorporate/src/backend/templates/social-networks/blogpost-badges.html
sites/funcorporate/src/backend/templates/social-networks/course-badges.html
sites/funcorporate/src/backend/templates/social-networks/footer-badges.html
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/templates/social-networks/blogpost-badges.html
sites/funmooc/src/backend/templates/social-networks/course-badges.html
sites/funmooc/src/backend/templates/social-networks/footer-badges.html

Some modifications to the `ademe` site were requested in issue https://github.com/openfun/fun-richie-site-factory/issues/97

🚸(ademe) minor Ux/wording customizations

---

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/src/backend/ademe/settings.py
sites/ademe/src/backend/base/context_processors.py
sites/ademe/src/backend/base/tests/test_template.py
sites/ademe/src/backend/templates/richie/base.html
sites/ademe/src/frontend/scss/_main.scss
sites/ademe/src/frontend/scss/components/libs/_tarteaucitron.scss
sites/ademe/src/frontend/scss/extras/colors/_theme.scss

Load Ademe tarteaucitron tag then customize its look'n feel to fit site one.
https://github.com/openfun/fun-richie-site-factory/assets/9265241/df4522a2-367f-453f-a42a-eeb76db67e23

✨(ademe) setup tarteaucitron

---

.circleci/config.yml
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/funmooc/settings.py

Richie will fetch an endpoint requiring the use of a bearer token. For this a setting JOANIE_API_KEY is used.

🔧(funmooc) add settings API_TOKEN for JOANIE_BACKEND

---

sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Bump richie to 2.28.0 then release minor version of FUN Mooc

🔖(funmooc) bump to version 1.34.0 

---

.circleci/config.yml
sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Bump to version 1.34.1

---

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/requirements/base.txt
sites/ademe/src/frontend/js/components/CourseGlimpse/index.tsx
sites/ademe/src/frontend/package.json
sites/ademe/src/frontend/scss/_main.scss
sites/ademe/src/frontend/scss/extras/colors/_theme.scss
sites/ademe/src/frontend/tsconfig.json
sites/ademe/src/frontend/yarn.lock

There is currently an issue when the loading of the lti consumer plugin. Upgrading to richie 2.28.1 fix this issue.

⬆️(ademe) upgrade richie to 2.28.1

---

sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

funmooc-1.35.1

---

.circleci/config.yml
sites/funmooc/src/frontend/scss/components/_header.scss

First justify to left the menu items, then try to improve vertical alignment between menu items and user menu.
| Before | After |
|--------|-------|
|<img width="1238" alt="Capture d’écran 2024-10-08 à 17 08 22" src="https://github.com/user-attachments/assets/959c0991-1ee2-46e8-9bf5-dab5a8dfb406">|<img width="1237" alt="Capture d’écran 2024-10-08 à 17 08 02" src="https://github.com/user-attachments/assets/e9fbc94c-1b19-40e0-a77f-078187a1bef7">|

💄(funmooc) fix some minor issues on new header layout

---

.circleci/config.yml
sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/scss/extras/colors/_theme.scss
sites/funmooc/src/frontend/yarn.lock

Upgrade FUN Mooc to richie 2.30.0
https://github.com/openfun/richie/releases/tag/v2.30.0
Then release funmooc 1.36.0

⬆️(funmooc) upgrade to richie 2.30.0

---

sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Upgrade to richie 2.33.0 and release new version of fun mooc

Funmooc/richie 2.33.0

---

sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json

Added
- Add a middleware in charge of detecting malformed query strings

🔖(funmooc) bump to version 1.40.0

---

sites/funmooc/CHANGELOG.md
sites/funmooc/src/frontend/scss/extras/colors/_theme.scss
sites/funmooc/src/frontend/scss/objects/_course_glimpses.scss

Modify course glimpse theme to display offer price and hide offer icon when the course offer is free

💄(funmooc) hide free offer icon and show offer price

---

sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Changed
- Hide offer icon for free courses
- Show offer price

🔖(funmooc) bump to version 1.42.0-beta.3

---

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/src/backend/ademe/settings.py
sites/ademe/src/backend/base/middleware.py
sites/ademe/src/backend/base/tests/test_middleware.py
sites/funcampus/CHANGELOG.md
sites/funcampus/src/backend/base/middleware.py
sites/funcampus/src/backend/base/tests/test_middleware.py
sites/funcampus/src/backend/funcampus/settings.py
sites/funcorporate/CHANGELOG.md
sites/funcorporate/src/backend/base/middleware.py
sites/funcorporate/src/backend/base/tests/test_middleware.py
sites/funcorporate/src/backend/funcorporate/settings.py

Some bots are spamming fun campus by producing urls with malformed query strings.
In order to prevent this spam, as it was done on FUN MOOC (PR #251 and #254), we implement a middleware in charge of detect query strings then raise a BadRequest exception if one is detected.

✨(funcampus/funcorporate/ademe) add middleware to detect malformed query strings

---

sites/ademe/CHANGELOG.md
sites/ademe/src/backend/ademe/__init__.py
sites/ademe/src/frontend/package.json
sites/funcampus/CHANGELOG.md
sites/funcampus/src/backend/funcampus/__init__.py
sites/funcampus/src/frontend/package.json
sites/funcorporate/CHANGELOG.md
sites/funcorporate/src/backend/funcorporate/__init__.py
sites/funcorporate/src/frontend/package.json

- Add a middleware in charge of detecting malformed query strings
- Upgrade richie to 3.0.0
- Migrate to new STORAGES settings
- Add a middleware in charge of detecting malformed query strings
- Upgrade richie to 3.0.0
- Migrate to new STORAGES settings
- Add a middleware in charge of detecting malformed query strings
- Upgrade richie to 3.0.0

🔖(funcampus/funcorporate/ademe) bump to next minor versions

---

sites/ademe/CHANGELOG.md
sites/ademe/requirements/base.txt
sites/ademe/src/backend/ademe/__init__.py
sites/ademe/src/frontend/package.json
sites/ademe/src/frontend/yarn.lock
sites/demo/CHANGELOG.md
sites/demo/requirements/base.txt
sites/demo/src/backend/demo/__init__.py
sites/demo/src/frontend/package.json
sites/demo/src/frontend/yarn.lock
sites/funcampus/CHANGELOG.md
sites/funcampus/requirements/base.txt
sites/funcampus/src/backend/funcampus/__init__.py
sites/funcampus/src/frontend/package.json
sites/funcampus/src/frontend/yarn.lock
sites/funcorporate/CHANGELOG.md
sites/funcorporate/requirements/base.txt
sites/funcorporate/src/backend/funcorporate/__init__.py
sites/funcorporate/src/frontend/package.json
sites/funcorporate/src/frontend/yarn.lock
sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

- Upgrade richie to 3.1.1
- Upgrade richie to 3.1.1
- Upgrade richie to 3.1.1
- Upgrade richie to 3.1.1
- Upgrade richie to 3.1.1

🔖(ademe/demo/funcampus/funcorporate/funmooc) bump to next patch versions

---

.circleci/config.yml
sites/funmooc/requirements/base.txt
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

The latest dev version of richie includes course hidding
and we want to test that on fun mooc website. So we upgrade to the latest
dev version in order to prepare a new fun mooc beta version.

⬆️(funmooc) upgrade richie to v3.1.3.dev2

---

sites/ademe/CHANGELOG.md
sites/ademe/src/backend/ademe/__init__.py
sites/ademe/src/frontend/package.json
sites/funcampus/CHANGELOG.md
sites/funcampus/src/backend/funcampus/__init__.py
sites/funcampus/src/frontend/package.json
sites/funcorporate/CHANGELOG.md
sites/funcorporate/src/backend/funcorporate/__init__.py
sites/funcorporate/src/frontend/package.json
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json

Page creation via the CMS wizard is degraded with query string errors.
For all sites:
- Exclude CMS endpoints from malformed query parameters

🔖(ademe/funcampus/funcorporate/funmooc) bump to next patch version

---

.circleci/config.yml
sites/funmooc/requirements/base.txt
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Supersedes #280 
Update funmooc to v3.1.3.dev17

⬆(funmooc) upgrade richie to v3.1.3.dev17

---

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/requirements/base.txt
sites/ademe/src/backend/ademe/__init__.py
sites/ademe/src/frontend/package.json
sites/ademe/src/frontend/yarn.lock
sites/demo/CHANGELOG.md
sites/demo/requirements/base.txt
sites/demo/src/backend/demo/__init__.py
sites/demo/src/frontend/package.json
sites/demo/src/frontend/yarn.lock
sites/funcampus/CHANGELOG.md
sites/funcampus/requirements/base.txt
sites/funcampus/src/backend/funcampus/__init__.py
sites/funcampus/src/frontend/package.json
sites/funcampus/src/frontend/yarn.lock
sites/funcorporate/CHANGELOG.md
sites/funcorporate/requirements/base.txt
sites/funcorporate/src/backend/funcorporate/__init__.py
sites/funcorporate/src/frontend/package.json
sites/funcorporate/src/frontend/yarn.lock
sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

- Upgrade richie to 3.2.0
- Upgrade richie to 3.2.0
- Upgrade richie to 3.2.0
- Upgrade richie to 3.2.0
- Replace Paid offer color (eastern-blue) with #088488
- Use glimpse footer color for glimpse label icon
- Upgrade richie to 3.2.0

🔖(ademe/demo/funcampus/funcorporate/funmooc) bump to next minor versions

---

sites/funmooc/requirements/base.txt
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Changelog available at:
https://github.com/openfun/richie/releases/tag/v3.2.1-dev11

⬆️(funmooc) upgrade richie to v3.2.1-dev11
