.circleci/config.yml
env.d/development

Since docker compose 2.7.0, there is an "Invalid template" error when a
environment variable which is a regex is not quoted. This is the case of
`EDX_SELECTOR_REGEX` and `EDX_COURSE_REGEX`. So we quote those two variables.

🐛(env.d) fix env compatibility issue with docker compose 2.7.0

---

.circleci/config.yml
Dockerfile
sites/ademe/CHANGELOG.md
sites/ademe/requirements/base.txt
sites/ademe/src/frontend/package.json
sites/ademe/src/frontend/yarn.lock
sites/cnfpt/CHANGELOG.md
sites/cnfpt/requirements/base.txt
sites/cnfpt/src/frontend/package.json
sites/cnfpt/src/frontend/yarn.lock
sites/demo/CHANGELOG.md
sites/demo/requirements/base.txt
sites/demo/src/frontend/package.json
sites/demo/src/frontend/yarn.lock
sites/funcampus/CHANGELOG.md
sites/funcampus/requirements/base.txt
sites/funcampus/src/frontend/package.json
sites/funcampus/src/frontend/yarn.lock
sites/funcorporate/CHANGELOG.md
sites/funcorporate/requirements/base.txt
sites/funcorporate/src/frontend/package.json
sites/funcorporate/src/frontend/yarn.lock
sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Currently we are not able to merge PR in this repository as richie dependency contains error that breaks job ci. Richie 2.15.1 has been released to fix those errors.
Furthermore, django cms 3.11 has been released recently and we have updated our fork so we are now able to use this new version in our sites.
Then dependency bot warns us about a security issue with the javascript package terser so we embedded this update in this PR.

Upgrade dependencies

---

.circleci/config.yml
.circleci/src/workflows/site_jobs.yml.tpl

## Purpose
We generate automatically circle ci configuration file according to modification. But currently, except for the job "hub", filter tag expression is not prefix by a '^'. It could lead to a misbehaviour if a site name includes another site name.
e.g :
If we have two sites : 
- demo
- ademo
ademo tags will also trigger jobs of demo site : `demo-.*` and `ademo-.*`

💚(site_jobs) prefix all filter tags regex with ^

---

.circleci/config.yml
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po
sites/funmooc/src/backend/templates/richie/base.html

The "help" button now redirects to a FAQ page so we want also to change the label of this button to "FAQ".

💬(funmooc) change help button label into FAQ

---

sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/base/static/funmooc/js/xiti.js
sites/funmooc/src/frontend/js/utils/api/web-analytics/xiti.ts

ATInternet will deprecate soon its Analytics Suite 2 in favor of Piano Analytics. Currently, to send analytic events we are using smartTag SDK which is able to send data to Piano Analytics but not in an optimal way.
So we take the opportunity of the deprecation of AS2 to switch to the new Piano Analytics SDK to send analytics event.

📈(xiti) migrate to piano analytics

---

sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/funmooc/settings.py
sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po

We want to add Pashto as an possible language for course runs.
- Add Pashto (ps) to the `ALL_LANGUAGES` setting
- Fix demo site that was broken since we added an internal link to the home page pointing a page with reverse ID set to "help".

Add Pashto language to funmooc

---

sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/base/static/funmooc/js/xiti.js

The method to deserialize an analytic dimension returned a single value when the dimension could not be split. But, about organizations, we need to always manage an array so in the case where a page contained only one organization, the xiti tag initialization failed. 
https://sentry.io/share/issue/b30cd972525c4313b4814adf5743aaf1/

🐛(funmooc) fix xiti issues when a page has only one organization

---

.circleci/config.yml
.circleci/src/jobs/@backend.yml
bin/upgrade
sites/ademe/CHANGELOG.md
sites/ademe/requirements/base.txt
sites/ademe/requirements/dev.txt
sites/ademe/src/backend/ademe/settings.py
sites/ademe/src/backend/locale/fr/LC_MESSAGES/django.po
sites/ademe/src/frontend/package.json
sites/ademe/src/frontend/yarn.lock
sites/cnfpt/requirements/dev.txt
sites/demo/requirements/dev.txt
sites/funcampus/requirements/dev.txt
sites/funcorporate/requirements/dev.txt
sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/requirements/dev.txt
sites/funmooc/src/backend/funmooc/settings.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/scss/_main.scss
sites/funmooc/src/frontend/scss/extras/colors/_theme.scss
sites/funmooc/src/frontend/yarn.lock

We want to upgrade `funmooc` and `ademe` sites to richie v2.17.0.

Upgrade to richie 2.17.0 for the funmooc and ademe sites

---

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/src/frontend/scss/extras/colors/_theme.scss
sites/funmooc/CHANGELOG.md
sites/funmooc/src/frontend/scss/extras/colors/_theme.scss

When no opened course runs are available, a label is displayed to explain that to the user but currently the shade difference between the color label and its background does not comply with RGAA on FUN Mooc and Ademe sites.
**It appears that currently a light color on a tealish background does not comply
at all with RGAA!** The only color that could be used is black. But currently, all
text in the course subheader is white so if we use a black color for this label
only we are breaking ui consistency.
In other hand, the new constrast color norm used by the WCAG next version 3,
APCA, challenges RGAA in this case. It appears that a pale-grey 16px bold text on a
tealish background could comply with APCA. So as a take-off, in order to improve
accessibility and keep ui consistency, we could use …

♿  a11y/empty course label

---

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/src/backend/ademe/urls.py
sites/ademe/src/backend/base/tests/test_views.py
sites/ademe/src/backend/base/urls.py
sites/ademe/src/backend/base/views.py

Following migration of the Ademe site to richie, We don't want to lose all the traffic previously directed to course syllabus on OpenEdX. 
Add a view that catches these urls and tries to redirect them to the corresponding course detail page in Richie or resort to the search page.

✨(ademe) add redirect for OpenEdX course urls

---

sites/ademe/CHANGELOG.md
sites/ademe/src/frontend/scss/extras/colors/_theme.scss

Currently, active pagination item has a black background that does not fit with the global website color palette. We replace this black color by dark-aquamarine in order to harmonize color palette.
|After|Before|
|-----|------|
|<img width="888" alt="image" src="https://github.com/openfun/fun-richie-site-factory/assets/9265241/979ae85d-7c1c-4d58-ae73-c932e5481fa6">|<img width="889" alt="image" src="https://github.com/openfun/fun-richie-site-factory/assets/9265241/1c977dcd-02b3-4c52-a783-62c097eafd39">|

💄(ademe) fix background color of active pagination item

---

.circleci/config.yml
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/base/static/funmooc/js/pianoanalytics.js
sites/funmooc/src/backend/base/static/funmooc/js/xiti.js
sites/funmooc/src/backend/base/tests/test_context_processors.py
sites/funmooc/src/backend/templates/richie/web_analytics.html
sites/funmooc/src/frontend/js/api/web-analytics/index.ts
sites/funmooc/src/frontend/js/api/web-analytics/pianoanalytics.ts

- Piano Analytics does not collect campaign marketing events with `utm_` prefix
- Web analytics integration uses the latest version available of the Piano JS SDK, exposing us to automatic upgrades and integration bugs
- Configure PA to also collect `utm_`-prefixed parameters
- Pin Piano Analytics JS SDK to 6.13.1

📈(piano) pin JS SDK and configure to collect UTM parameters

---

.circleci/config.yml
.circleci/src/jobs/@docker.yml
.circleci/src/jobs/@project.yml

Ubuntu images have been removed from circle-ci. We can use the default tags to
replace them.
Furthermore, the cimg/base image has a current tag we can use to avoid to have to
update them when circle will decide to remove old tags.

💚(circle) replace deprecated images

---

.circleci/config.yml
sites/funmooc/src/frontend/js/api/lms/dummy.ts

The job to build canary image currently fails.
https://app.circleci.com/pipelines/github/openfun/fun-richie-site-factory/561/workflows/d1a4c9ba-5bc6-404e-8b17-266121c142d1/jobs/14812
The next version of `richie-education` package rename `Enrollment` type into `UnknownEnrollment`. As we were using this type in an overridden module, `tsc` command raises an error and prevent the frontend to be built. In order to be able to build canary images without requiring to release a new version of Richie, we simply remove the use of the problematic type. As the impacted module is only reserved for development purpose, this workaround looks acceptable.

🩹️(funmooc) fix type issue that broke canary build

---

.circleci/config.yml
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/funmooc/settings.py

The default dashboard url is currently malformed. Indeed there is an extra slash at the end 
so the target is currently a 404 page...

🚑(funmooc) fix malformed dashboard url

---

sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/base/templates/cms/professional_training_detail.html
sites/funmooc/src/backend/base/tests/test_template.py
sites/funmooc/src/backend/funmooc/settings.py
sites/funmooc/src/backend/locale/fr/LC_MESSAGES/django.po

We are preparing professional training on FUN Mooc and we would like to use more relevant jargon for this kind of course so we decide to create a custom course page template which extends to the course detail template.

✨(funmooc) add custom course template for professional training

---

.circleci/config.yml
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/backend/funmooc/settings.py
sites/funmooc/src/frontend/package.json

With Django 4, the setting `CSRF_TRUSTED_ORIGINS` may be required. So we add it
for the production configuration.
Then release a patch version of FUN Mooc.

🔧(funmooc) add missing CSRF_TRUSTED_ORIGINS settings

---

.circleci/config.yml
Dockerfile

Since an update of Docker, the build failed during python dependencies setup. It
appears there is a missing `&&` to chain two pip installs.
We also take opportunity of this change to fix the warning `FromAsCasing`.

🔧(docker) fix docker build

---

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/src/backend/ademe/settings.py
sites/ademe/src/backend/base/storage.py
sites/demo/CHANGELOG.md
sites/demo/src/backend/base/storage.py
sites/demo/src/backend/demo/settings.py
sites/funcampus/CHANGELOG.md
sites/funcampus/src/backend/base/storage.py
sites/funcampus/src/backend/funcampus/settings.py
sites/funcorporate/CHANGELOG.md
sites/funcorporate/src/backend/base/storage.py
sites/funcorporate/src/backend/funcorporate/settings.py

Except for FUN Mooc which is already migrated, all other sites settings must be updated to use the new django STORAGES settings added in Django 4.2 as without this migration, we are not able anymore to build a docker image.

🔧(all) migrate to new STORAGES settings

---

sites/ademe/CHANGELOG.md
sites/ademe/requirements/base.txt
sites/ademe/src/backend/ademe/settings.py

Ademe python dependencies were too old, we upgrade them to match version used on
FUN Mooc. This include a migration to Sentry SDK 2.0

⬆️(ademe) upgrade python dependencies

---

.circleci/config.yml
Dockerfile
sites/ademe/requirements/base.txt
sites/demo/requirements/base.txt
sites/funcampus/requirements/base.txt
sites/funcorporate/requirements/base.txt
sites/funmooc/requirements/base.txt

Currently, we are installing our django-cms fork through a command ran into the Dockerfile. Since an update of Docker, we had recently to update this command but this introduced a bug which leads to install Django 5.x when installing our fork. In order to keep django version constraint, we decide to add our fork into
each base.txt requirements file of each our sites.

🔧(requirements) add django-cms fork into requirements

---

sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Upgrade to richie 2.29.2 then release a patch version of Richie
https://github.com/openfun/richie/releases/tag/v2.29.2

⬆️(funmooc) upgrade to richie 2.29.2

---

.circleci/config.yml
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/templates/courses/cms/course_detail.html
sites/funmooc/src/backend/templates/richie/base.html
sites/funmooc/src/frontend/scss/_main.scss
sites/funmooc/src/frontend/scss/components/_header.scss
sites/funmooc/src/frontend/scss/extras/settings/_variables.scss
sites/funmooc/src/frontend/scss/objects/_breadcrumbs.scss

Purpose of this PR is to change header structure so the main menu are moved up aside brand logo and search bar have been moved down aside breadcrumbs.
- Since in the demo the main menu is too large for the available space, the signup button has been hided from CSS but frontend developer may prefer to do this at the richie-react login module level;
- Base template disable the `topbar_contact` block content since funmooc was using it for the FAQ link which will be moved somewhere else further;
- Breadcrumb part has been changed to include the search bar aside;
- Sass changes on different components and objects have been made to perform the header and breadcrumbs adjustments;
- Also some space adjustments have been made on header for` >1024px`,`<xl` breakpoints to  ensure the main menu will …

🍱(funmooc) Update 'funmooc' site integration to move up main menu and move down the search bar

---

.circleci/config.yml
Dockerfile
docker-compose.yml

The collector step in the Dockerfile is made using the richie version set in the backend requirements. If new statics are added in the next tag then they will not be present. To fix that, the uninstallation of richie and the installtion of the next version is made in the core stage. Doing that, the canary stage is not needed anymore and the argument BUILD_NEXT_FRONT is rename in BUILD_NEXT_VERSION to be more accurate.

🐛(canary) collector step must be made with the richie next version

---

sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/base/middleware.py
sites/funmooc/src/backend/base/tests/test_middleware.py
sites/funmooc/src/backend/base/tests/test_template.py
sites/funmooc/src/backend/funmooc/settings.py

Some bots are spamming fun mooc by producing urls with malformed query strings. In order to prevent this spam, we implement a middleware in charge of cleaning query strings then redirect to a clean url if needed.

✨(funmooc) add middleware to clean query strings

---

.circleci/config.yml
sites/ademe/requirements/base.txt
sites/demo/requirements/base.txt
sites/funcampus/requirements/base.txt
sites/funcorporate/requirements/base.txt
sites/funmooc/requirements/base.txt

We recently upgrade our fork of django cms to the
latest 3.x version. So now we use this version in our factory.
https://github.com/openfun/django-cms/releases/tag/fun-3.11.9

⬆️(all) upgrade to django-cms 3.11.9

---

.circleci/config.yml
sites/ademe/CHANGELOG.md
sites/ademe/requirements/base.txt
sites/ademe/src/backend/ademe/__init__.py
sites/ademe/src/frontend/package.json
sites/ademe/src/frontend/yarn.lock
sites/demo/CHANGELOG.md
sites/demo/requirements/base.txt
sites/demo/src/backend/demo/__init__.py
sites/demo/src/frontend/package.json
sites/demo/src/frontend/yarn.lock
sites/funcampus/CHANGELOG.md
sites/funcampus/requirements/base.txt
sites/funcampus/src/backend/funcampus/__init__.py
sites/funcampus/src/frontend/package.json
sites/funcampus/src/frontend/yarn.lock
sites/funcorporate/CHANGELOG.md
sites/funcorporate/requirements/base.txt
sites/funcorporate/src/backend/funcorporate/__init__.py
sites/funcorporate/src/frontend/package.json
sites/funcorporate/src/frontend/yarn.lock
sites/funmooc/CHANGELOG.md
sites/funmooc/requirements/base.txt
sites/funmooc/src/backend/funmooc/__init__.py
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

- Upgrade richie to 3.1.0
- Upgrade richie to 3.1.0
- Upgrade richie to 3.0.0
- Migrate to new STORAGES settings
- Upgrade richie to 3.1.0
- Upgrade richie to 3.1.0
- Upgrade richie to 3.1.0
- Upgrade all deps

🔖(ademe/demo/funcampus/funcorporate/funmooc) bump to next minor versions

---

.circleci/config.yml
docs/scw.md
scw/s3.tf
sites/ademe/CHANGELOG.md
sites/ademe/scw/config.tfvars
sites/ademe/src/backend/ademe/settings.py
sites/demo/CHANGELOG.md
sites/demo/scw/config.tfvars
sites/demo/src/backend/demo/settings.py
sites/funcampus/CHANGELOG.md
sites/funcampus/scw/config.tfvars
sites/funcampus/src/backend/funcampus/settings.py
sites/funcorporate/CHANGELOG.md
sites/funcorporate/scw/config.tfvars
sites/funcorporate/src/backend/funcorporate/settings.py
sites/funmooc/CHANGELOG.md
sites/funmooc/src/backend/funmooc/settings.py

Media files can now be stored on Scaleway instead of AWS.
Static files are no longer proxied through a CDN, as Scaleway Edge Services do not support this feature.
To be able to change the custom domain for media files without interfering with static files, we are not using the `MediaStorage` backend anymore but the `S3Storage` backend along with its associated `AWS`-prefixed settings. 
We are also using the `CDNManifestStaticFileStorage` backend with an undefined `CDN_DOMAIN` setting to use the custom `post_process` method.
An IAM policy had to be added for the IAM application so it can read and write in the media buckets.

🧱(funcorporate) migrate media storage to Scaleway and drop CDN static proxy

---

sites/funmooc/requirements/base.txt
sites/funmooc/src/frontend/package.json
sites/funmooc/src/frontend/yarn.lock

Changelog available at:
https://github.com/openfun/richie/releases/tag/v3.1.3.dev27

⬆(funmooc) upgrade richie to v3.1.3.dev27

---

.circleci/config.yml
sites/demo/CHANGELOG.md
sites/demo/src/backend/demo/settings.py

The bucket `production-demo-media` was created on Scaleway following the same naming convention as other sites (\<environment\>-\<site\>-media). 
Update all demo bucket names from `<environment>-richie-media` to `<environment>-demo-media`.

🚚(demo) update S3 bucket names to match provisioned on Scaleway

---

sites/demo/CHANGELOG.md
sites/demo/src/backend/demo/__init__.py
sites/demo/src/frontend/package.json

- Update S3 bucket names to match those provisioned on Scaleway

🔖(demo) bump to version 1.29.1
